package ru.baldursgate3.tgbot.bot.enums;

public enum UserState {
    CHANGING_CHARACTER_NAME,
    CHANGING_CHARACTER_STR,
    CHANGING_CHARACTER_DEX,
    CHANGING_CHARACTER_CON,
    CHANGING_CHARACTER_INT,
    CHANGING_CHARACTER_WIS,
    CHANGING_CHARACTER_CHA,
    DEFAULT

}
